# docker pull jaroslavtyc/drd.info:latest && docker-compose build
version: "3"
services:
  docker.drd.info:
    image: jaroslavtyc/drd.info
    environment:
      PROJECT_ENVIRONMENT: "prod"
    volumes:
      - ./.docker/root:/root
      - ./.docker/etc/caddy:/etc/caddy
    ports:
      - "80:80"
      - "443:443"
    restart: "always"
    networks:
      - default
      - proxy

networks:
  proxy:
    external:
      name: docker-www
